//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Syracuse.Mobitheque.Core.ApplicationResource", typeof(ApplicationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are on hold.
        /// </summary>
        public static string AccountInfoCountAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountAvailableBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is late.
        /// </summary>
        public static string AccountInfoCountLateLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are late.
        /// </summary>
        public static string AccountInfoCountLateLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountLateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No booking available at the moment.
        /// </summary>
        public static string AccountInfoCountNotAvailableBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountNotAvailableBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You borrowed {0} document.
        /// </summary>
        public static string AccountInfoCountOfBooking {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reserved {0} documents.
        /// </summary>
        public static string AccountInfoCountOfBookings {
            get {
                return ResourceManager.GetString("AccountInfoCountOfBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reserved {0} document.
        /// </summary>
        public static string AccountInfoCountOfLoan {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You borrowed {0} documents.
        /// </summary>
        public static string AccountInfoCountOfLoans {
            get {
                return ResourceManager.GetString("AccountInfoCountOfLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoan {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} are to be returned on {1}.
        /// </summary>
        public static string AccountInfoReturnDateLoans {
            get {
                return ResourceManager.GetString("AccountInfoReturnDateLoans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are logged in as {0}.
        /// </summary>
        public static string AccountSwitchSuccess {
            get {
                return ResourceManager.GetString("AccountSwitchSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to cancel the following booking :
        ///{0}
        ///Cancellation is final..
        /// </summary>
        public static string BookingCancelChoice {
            get {
                return ResourceManager.GetString("BookingCancelChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booked on {0}.
        /// </summary>
        public static string BookingResultBookingDate {
            get {
                return ResourceManager.GetString("BookingResultBookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bookings.
        /// </summary>
        public static string Bookings {
            get {
                return ResourceManager.GetString("Bookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonValidation {
            get {
                return ResourceManager.GetString("ButtonValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} .
        /// </summary>
        public static string DateToDate {
            get {
                return ResourceManager.GetString("DateToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From {0} to {1} from {2} to {3}.
        /// </summary>
        public static string DateToDateHours {
            get {
                return ResourceManager.GetString("DateToDateHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} from {1}  to {2}.
        /// </summary>
        public static string DateToDateShort {
            get {
                return ResourceManager.GetString("DateToDateShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be temporarily logged out of your current session. Once the new account has been added, you can switch from one to the other in one click..
        /// </summary>
        public static string DisconectAuthorization {
            get {
                return ResourceManager.GetString("DisconectAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string DisponibilityNo {
            get {
                return ResourceManager.GetString("DisponibilityNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string DisponibilityYes {
            get {
                return ResourceManager.GetString("DisponibilityYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} has not been uploaded.
        ///
        ///The error is as follows: 
        ///{1}.
        /// </summary>
        public static string DownloadGetFileError {
            get {
                return ResourceManager.GetString("DownloadGetFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation request has failed.
        /// </summary>
        public static string FailBookingRequest {
            get {
                return ResourceManager.GetString("FailBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal Impossible.
        /// </summary>
        public static string FailExtendLoan {
            get {
                return ResourceManager.GetString("FailExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you forget this account on the application? You can always log back in to it later..
        /// </summary>
        public static string ForgetAccount {
            get {
                return ResourceManager.GetString("ForgetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voulez-vous confirmer votre reservation à {0}.
        /// </summary>
        public static string HoldingChoice {
            get {
                return ResourceManager.GetString("HoldingChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available to {0}.
        /// </summary>
        public static string HoldingDisponibilityText {
            get {
                return ResourceManager.GetString("HoldingDisponibilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected return on {0} at {1}.
        /// </summary>
        public static string HoldingDisponibilityTextDateBack {
            get {
                return ResourceManager.GetString("HoldingDisponibilityTextDateBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My establishment.
        /// </summary>
        public static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My loans.
        /// </summary>
        public static string Loans {
            get {
                return ResourceManager.GetString("Loans", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return on .
        /// </summary>
        public static string LoansDateBefore {
            get {
                return ResourceManager.GetString("LoansDateBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late since the .
        /// </summary>
        public static string LoansDateLate {
            get {
                return ResourceManager.GetString("LoansDateLate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in this field.
        /// </summary>
        public static string MissingField {
            get {
                return ResourceManager.GetString("MissingField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This feature requires a network connection, please check this before trying again..
        /// </summary>
        public static string NetworkDisable {
            get {
                return ResourceManager.GetString("NetworkDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View online.
        /// </summary>
        public static string OnlineConsult {
            get {
                return ResourceManager.GetString("OnlineConsult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were not able to open this file.
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my accounts.
        /// </summary>
        public static string OtherAccount {
            get {
                return ResourceManager.GetString("OtherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinned documents.
        /// </summary>
        public static string PinnedDocuments {
            get {
                return ResourceManager.GetString("PinnedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News of the day.
        /// </summary>
        public static string PressDaily {
            get {
                return ResourceManager.GetString("PressDaily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International News.
        /// </summary>
        public static string PressInternational {
            get {
                return ResourceManager.GetString("PressInternational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to extend this copy?
        ///{0}.
        /// </summary>
        public static string RenewChoice {
            get {
                return ResourceManager.GetString("RenewChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning a book.
        /// </summary>
        public static string Scan {
            get {
                return ResourceManager.GetString("Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results.
        /// </summary>
        public static string SearchViewResultCount {
            get {
                return ResourceManager.GetString("SearchViewResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} result.
        /// </summary>
        public static string SearchViewResultNull {
            get {
                return ResourceManager.GetString("SearchViewResultNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to Z (Author).
        /// </summary>
        public static string SortOptionAutorASC {
            get {
                return ResourceManager.GetString("SortOptionAutorASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z to A (Author).
        /// </summary>
        public static string SortOptionAutorDESC {
            get {
                return ResourceManager.GetString("SortOptionAutorDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pertinence.
        /// </summary>
        public static string SortOptionPertinence {
            get {
                return ResourceManager.GetString("SortOptionPertinence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to most recent.
        /// </summary>
        public static string SortOptionTimeASC {
            get {
                return ResourceManager.GetString("SortOptionTimeASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to less recent.
        /// </summary>
        public static string SortOptionTimeDESC {
            get {
                return ResourceManager.GetString("SortOptionTimeDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A to Z (Title).
        /// </summary>
        public static string SortOptionTitleASC {
            get {
                return ResourceManager.GetString("SortOptionTitleASC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z to A (Title).
        /// </summary>
        public static string SortOptionTitleDESC {
            get {
                return ResourceManager.GetString("SortOptionTitleDESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document will be made available to you shortly..
        /// </summary>
        public static string SuccessBookingRequest {
            get {
                return ResourceManager.GetString("SuccessBookingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your booking has been cancelled for the title {0}.
        /// </summary>
        public static string SuccessCancelBooking {
            get {
                return ResourceManager.GetString("SuccessCancelBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bookings has been extended for the title {0}.
        /// </summary>
        public static string SuccessExtendLoan {
            get {
                return ResourceManager.GetString("SuccessExtendLoan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
