//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Syracuse.Mobitheque.UI {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Syracuse.Mobitheque.UI.AppResource.fr", typeof(AppResource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AboutCopyright {
            get {
                return ResourceManager.GetString("AboutCopyright", resourceCulture);
            }
        }
        
        public static string AboutMailContact {
            get {
                return ResourceManager.GetString("AboutMailContact", resourceCulture);
            }
        }
        
        public static string AboutRigth {
            get {
                return ResourceManager.GetString("AboutRigth", resourceCulture);
            }
        }
        
        public static string AboutVersion {
            get {
                return ResourceManager.GetString("AboutVersion", resourceCulture);
            }
        }
        
        public static string AboutWebLink {
            get {
                return ResourceManager.GetString("AboutWebLink", resourceCulture);
            }
        }
        
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        public static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        public static string AddAccountTuto {
            get {
                return ResourceManager.GetString("AddAccountTuto", resourceCulture);
            }
        }
        
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        public static string BookingAvailable {
            get {
                return ResourceManager.GetString("BookingAvailable", resourceCulture);
            }
        }
        
        public static string BookingWait {
            get {
                return ResourceManager.GetString("BookingWait", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        public static string CopiesCollectionStatements {
            get {
                return ResourceManager.GetString("CopiesCollectionStatements", resourceCulture);
            }
        }
        
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        public static string DeleteAppAccount {
            get {
                return ResourceManager.GetString("DeleteAppAccount", resourceCulture);
            }
        }
        
        public static string DepartmentTitle {
            get {
                return ResourceManager.GetString("DepartmentTitle", resourceCulture);
            }
        }
        
        public static string DigitalDocumentLink {
            get {
                return ResourceManager.GetString("DigitalDocumentLink", resourceCulture);
            }
        }
        
        public static string ErrorLibraryWebSite {
            get {
                return ResourceManager.GetString("ErrorLibraryWebSite", resourceCulture);
            }
        }
        
        public static string Extend {
            get {
                return ResourceManager.GetString("Extend", resourceCulture);
            }
        }
        
        public static string FilterOption {
            get {
                return ResourceManager.GetString("FilterOption", resourceCulture);
            }
        }
        
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        public static string LibraryTitle {
            get {
                return ResourceManager.GetString("LibraryTitle", resourceCulture);
            }
        }
        
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        public static string LoadMore {
            get {
                return ResourceManager.GetString("LoadMore", resourceCulture);
            }
        }
        
        public static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        public static string NeverShowAgain {
            get {
                return ResourceManager.GetString("NeverShowAgain", resourceCulture);
            }
        }
        
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        public static string NoSearchResults {
            get {
                return ResourceManager.GetString("NoSearchResults", resourceCulture);
            }
        }
        
        public static string NotCurrentBooking {
            get {
                return ResourceManager.GetString("NotCurrentBooking", resourceCulture);
            }
        }
        
        public static string NotCurrentEvent {
            get {
                return ResourceManager.GetString("NotCurrentEvent", resourceCulture);
            }
        }
        
        public static string NotCurrentLoan {
            get {
                return ResourceManager.GetString("NotCurrentLoan", resourceCulture);
            }
        }
        
        public static string OtherAccountPart2Tuto {
            get {
                return ResourceManager.GetString("OtherAccountPart2Tuto", resourceCulture);
            }
        }
        
        public static string OtherAccountPart3Tuto {
            get {
                return ResourceManager.GetString("OtherAccountPart3Tuto", resourceCulture);
            }
        }
        
        public static string OtherAccountPartTuto {
            get {
                return ResourceManager.GetString("OtherAccountPartTuto", resourceCulture);
            }
        }
        
        public static string OtherAccountTitleTuto {
            get {
                return ResourceManager.GetString("OtherAccountTitleTuto", resourceCulture);
            }
        }
        
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        public static string PasswordForget {
            get {
                return ResourceManager.GetString("PasswordForget", resourceCulture);
            }
        }
        
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        public static string SortOption {
            get {
                return ResourceManager.GetString("SortOption", resourceCulture);
            }
        }
        
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        public static string SwitchAccount {
            get {
                return ResourceManager.GetString("SwitchAccount", resourceCulture);
            }
        }
        
        public static string SwitchDeleteAccountPopupTitle {
            get {
                return ResourceManager.GetString("SwitchDeleteAccountPopupTitle", resourceCulture);
            }
        }
        
        public static string Synthesis {
            get {
                return ResourceManager.GetString("Synthesis", resourceCulture);
            }
        }
        
        public static string Validate {
            get {
                return ResourceManager.GetString("Validate", resourceCulture);
            }
        }
    }
}
